/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;

import Frames.AddBusFrame;
import Frames.AddEventFrame;
import Frames.DeleteBusFrame;
import Frames.DeleteEventFrame;
import java.awt.Desktop;
import static java.awt.SystemColor.desktop;

/**
 *
 * @author Sohaib Ali
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        admincontrolsmenu = new javax.swing.JMenu();
        logoutitem = new javax.swing.JMenuItem();
        addeventitem = new javax.swing.JMenuItem();
        addbusitem = new javax.swing.JMenuItem();
        deleteeventitem = new javax.swing.JMenuItem();
        deletebusitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(504, 410));
        setMinimumSize(new java.awt.Dimension(504, 410));
        setPreferredSize(new java.awt.Dimension(504, 410));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 500, 390);

        admincontrolsmenu.setText("Admin Controls");

        logoutitem.setText("LogOut");
        logoutitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutitemActionPerformed(evt);
            }
        });
        admincontrolsmenu.add(logoutitem);

        addeventitem.setText("Add Event");
        addeventitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addeventitemActionPerformed(evt);
            }
        });
        admincontrolsmenu.add(addeventitem);

        addbusitem.setText("Add Bus Service");
        addbusitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbusitemActionPerformed(evt);
            }
        });
        admincontrolsmenu.add(addbusitem);

        deleteeventitem.setText("Delete Event");
        deleteeventitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteeventitemActionPerformed(evt);
            }
        });
        admincontrolsmenu.add(deleteeventitem);

        deletebusitem.setText("Delete Bus Service");
        deletebusitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebusitemActionPerformed(evt);
            }
        });
        admincontrolsmenu.add(deletebusitem);

        jMenuBar1.add(admincontrolsmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutitemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutitemActionPerformed

    private void addeventitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addeventitemActionPerformed
        // TODO add your handling code here:
        AddEventFrame f = new AddEventFrame();
        desktop.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_addeventitemActionPerformed

    private void addbusitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbusitemActionPerformed
        // TODO add your handling code here:
        AddBusFrame f = new AddBusFrame();
        desktop.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_addbusitemActionPerformed

    private void deleteeventitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteeventitemActionPerformed
        // TODO add your handling code here:
        DeleteEventFrame f = new DeleteEventFrame();
        desktop.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_deleteeventitemActionPerformed

    private void deletebusitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebusitemActionPerformed
        // TODO add your handling code here:
        DeleteBusFrame f  = new DeleteBusFrame();
        desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_deletebusitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addbusitem;
    private javax.swing.JMenuItem addeventitem;
    private javax.swing.JMenu admincontrolsmenu;
    private javax.swing.JMenuItem deletebusitem;
    private javax.swing.JMenuItem deleteeventitem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutitem;
    // End of variables declaration//GEN-END:variables
}
