/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;


import java.sql.*;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static pkg1920x1080project.LogInPage.LoggedInUsername;

/**
 *
 * @author Sohaib Ali
 */
public class editprofilepage extends javax.swing.JFrame {

    /**
     * Creates new form editprofilepage
     */
    public editprofilepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatebtn = new javax.swing.JButton();
        emaillabel = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        homebtn = new javax.swing.JButton();
        passwordlabel1 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn);
        updatebtn.setBounds(690, 450, 150, 50);

        emaillabel.setText("Email");
        getContentPane().add(emaillabel);
        emaillabel.setBounds(70, 250, 100, 40);

        contactlabel.setText("Contact");
        getContentPane().add(contactlabel);
        contactlabel.setBounds(70, 400, 100, 40);
        getContentPane().add(emailfield);
        emailfield.setBounds(200, 260, 240, 22);

        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield);
        contactfield.setBounds(200, 410, 240, 22);

        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(homebtn);
        homebtn.setBounds(590, 443, 60, 60);

        passwordlabel1.setText("PASSWORD :");
        getContentPane().add(passwordlabel1);
        passwordlabel1.setBounds(70, 330, 100, 40);

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordfield);
        passwordfield.setBounds(200, 340, 240, 22);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EDIT PROFILE1366X768.png"))); // NOI18N
        getContentPane().add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String username = LoggedInUsername;
        
        Connection con;
        try {
            
            
            String email = emailfield.getText();
            String password = passwordfield.getText();
            String contact = contactfield.getText();
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = "Update `scd_db`.`Customer` set `Email` = ? , `Password` = ?, `Contact` = ? where `scd_db`.`Customer`.`Name` = ?";
            PreparedStatement ps =con.prepareStatement(sql);  

            ps.setString(1, email);
            ps.setString(2, password);
            ps.setString(3, contact);
            ps.setString(4, username);

            ps.executeUpdate();
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(editprofilepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactfieldActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        try {
            // TODO add your handling code here:
            homepage = new HomePage();
        } catch (SQLException ex) {
            Logger.getLogger(editprofilepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homebtnActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofilepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprofilepage().setVisible(true);
            }
        });
    }

    
    private HomePage homepage;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JButton homebtn;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JLabel passwordlabel1;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
