/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;

import java.sql.*;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sohaib Ali
 */
public class EventsPage extends javax.swing.JFrame {

    /**
     * Creates new form EventsPage
     */
    
    
    public static String SelectedEvent;
    
    public EventsPage() throws SQLException {
        initComponents();
        
        
        getBusServicesFromDB();
    }
    
    public void getBusServicesFromDB() throws SQLException
    {
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select * from `scd_db`.`Event`";
        PreparedStatement ps =con.prepareStatement(sql); 
        ResultSet rs = ps.executeQuery();
        
        DefaultTableModel tbModel = (DefaultTableModel)eventstable.getModel();
        for (int i = eventstable.getRowCount() - 1; i >= 0; i--) {
            tbModel.removeRow(i);
        }
        
        while(rs.next())
        {
            String eventname = rs.getString("Name");
            String location = rs.getString("Location");
            String time = rs.getString("Date");
            
            String tbData[] = {eventname, location, time};
            
            
            tbModel.addRow(tbData);

        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        eventstable = new javax.swing.JTable();
        viewdetailsbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        eventsbtn = new javax.swing.JButton();
        busbtn = new javax.swing.JButton();
        cartbtn = new javax.swing.JButton();
        reservedbtn = new javax.swing.JButton();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        eventstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event Name", "Location", "Time"
            }
        ));
        jScrollPane1.setViewportView(eventstable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 320, 1070, 370);

        viewdetailsbtn.setText("VIEW DETAILS");
        viewdetailsbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewdetailsbtn);
        viewdetailsbtn.setBounds(940, 170, 160, 60);

        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(homebtn);
        homebtn.setBounds(20, 123, 50, 70);

        eventsbtn.setContentAreaFilled(false);
        eventsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eventsbtn);
        eventsbtn.setBounds(20, 233, 50, 50);

        busbtn.setContentAreaFilled(false);
        busbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busbtnActionPerformed(evt);
            }
        });
        getContentPane().add(busbtn);
        busbtn.setBounds(10, 353, 60, 50);

        cartbtn.setContentAreaFilled(false);
        cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cartbtn);
        cartbtn.setBounds(20, 453, 50, 60);

        reservedbtn.setContentAreaFilled(false);
        reservedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(reservedbtn);
        reservedbtn.setBounds(20, 563, 50, 60);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EVENTS1366X768.png"))); // NOI18N
        getContentPane().add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        try {
            // TODO add your handling code here:
            homepage = new HomePage();
        } catch (SQLException ex) {
            Logger.getLogger(EventsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homebtnActionPerformed

    private void eventsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsbtnActionPerformed
        // TODO add your handling code here:
        //do nothing as already on this page
    }//GEN-LAST:event_eventsbtnActionPerformed

    private void busbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busbtnActionPerformed
        // TODO add your handling code here:
        busservicespage = new BusServices();
        busservicespage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_busbtnActionPerformed

    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartbtnActionPerformed

    private void reservedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservedbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservedbtnActionPerformed

    private void viewdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsbtnActionPerformed
        // TODO add your handling code here:
        
        int row = eventstable.getSelectedRow();
        
        String name = eventstable.getModel().getValueAt(row, 0).toString();
        System.out.print(name);
        
        SelectedEvent = name;
        
        this.dispose();
        ViewEventDetails ED;
        try {
            ED = new ViewEventDetails();
            ED.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EventsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_viewdetailsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EventsPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EventsPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    private HomePage homepage;
    private BusServices busservicespage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JButton busbtn;
    private javax.swing.JButton cartbtn;
    private javax.swing.JButton eventsbtn;
    private javax.swing.JTable eventstable;
    private javax.swing.JButton homebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reservedbtn;
    private javax.swing.JButton viewdetailsbtn;
    // End of variables declaration//GEN-END:variables
}
