/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;

import java.sql.*;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static pkg1920x1080project.LogInPage.LoggedInUsername;

/**
 *
 * @author Sohaib Ali
 */
public class ReservationsPage extends javax.swing.JFrame {

    /**
     * Creates new form ReservationsPage
     */
    public ReservationsPage() throws SQLException {
        initComponents();
        
        populate();
    }
    
    private String getCustomerID()
    {
        try {
                Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select `scd_db`.`Customer`.`CustomerID` from `scd_db`.`Customer` where `scd_db`.`Customer`.`Name` = ?";  
                PreparedStatement ps =con2.prepareStatement(sql);
                
                String name = LoggedInUsername;
                ps.setString(1, name);

                ResultSet rs1 = ps.executeQuery();
                rs1.next();
                
                String CustomerID = rs1.getString("CustomerID");
                System.out.println(CustomerID);
                
                return CustomerID;
            } catch (SQLException ex) {
                Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        return null;
        }
    
    public void populateEvents() throws SQLException
    {
        String CustomerID = getCustomerID(); 
        
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select * from `scd_db`.`EventReservation` inner join `scd_db`.`Event` on `scd_db`.`EventReservation`.`EventID` = `scd_db`.`Event`.`EventID` where `scd_db`.`EventReservation`.`CustomerID` = ?";
        PreparedStatement ps =con.prepareStatement(sql); 
        
        ps.setString(1, CustomerID);
        
        ResultSet rs = ps.executeQuery();
        
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
            tbModel.removeRow(i);
        }
        
        while(rs.next())
        {
            String name = rs.getString("Name");
            String quantity = rs.getString("EventQuantity");
            String date = rs.getString("Date");
            String SpecialCode = rs.getString("SpecialCode");
            
            String tbData[] = {name, quantity, date, SpecialCode};
            
            
            tbModel.addRow(tbData);

        }
    }
    
    public void populateBusService() throws SQLException
    {
        String CustomerID = getCustomerID(); 
        
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select * from `scd_db`.`BusServiceReservation` inner join `scd_db`.`BusService` on `scd_db`.`BusServiceReservation`.`BusServiceID` = `scd_db`.`BusService`.`BusServiceID` where `scd_db`.`BusServiceReservation`.`CustomerID` = ?";
        PreparedStatement ps =con.prepareStatement(sql); 
        
        ps.setString(1, CustomerID);
        
        ResultSet rs = ps.executeQuery();
        
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        
        while(rs.next())
        {
            String name = rs.getString("Name");
            String quantity = rs.getString("BusServiceQuantity");
            String date = rs.getString("Date");
            String SpecialCode = rs.getString("SpecialCode");
            
            String tbData[] = {name, quantity, date, SpecialCode};
            
            
            tbModel.addRow(tbData);

        }
    }
    
    public void populate() throws SQLException
    {
        // Name Quanitity Date TicketPrice
        
        populateEvents();
        populateBusService();
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        homebtn = new javax.swing.JButton();
        eventsbtn = new javax.swing.JButton();
        buservicesbtn = new javax.swing.JButton();
        cartbtn = new javax.swing.JButton();
        ignorebtn = new javax.swing.JButton();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Tickets Qty", "Date", "Special Code"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 360, 1080, 320);

        homebtn.setBorder(null);
        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(homebtn);
        homebtn.setBounds(10, 125, 60, 60);

        eventsbtn.setBorder(null);
        eventsbtn.setContentAreaFilled(false);
        eventsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eventsbtn);
        eventsbtn.setBounds(10, 240, 60, 50);

        buservicesbtn.setBorder(null);
        buservicesbtn.setContentAreaFilled(false);
        buservicesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buservicesbtnActionPerformed(evt);
            }
        });
        getContentPane().add(buservicesbtn);
        buservicesbtn.setBounds(13, 345, 60, 50);

        cartbtn.setBorder(null);
        cartbtn.setContentAreaFilled(false);
        cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cartbtn);
        cartbtn.setBounds(10, 450, 60, 60);

        ignorebtn.setBorder(null);
        ignorebtn.setContentAreaFilled(false);
        ignorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignorebtnActionPerformed(evt);
            }
        });
        getContentPane().add(ignorebtn);
        ignorebtn.setBounds(10, 565, 60, 50);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ReservationsPage1366x768.png"))); // NOI18N
        getContentPane().add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        try {        
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            homepage = new HomePage();
            homepage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_homebtnActionPerformed

    private void eventsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsbtnActionPerformed
        try {
            // TODO add your handling code here:
            eventspage = new EventsPage();
            eventspage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_eventsbtnActionPerformed

    private void buservicesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buservicesbtnActionPerformed
        try {
            // TODO add your handling code here:
            busservicespage = new BusServices();
            busservicespage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buservicesbtnActionPerformed

    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
        try {
            // TODO add your handling code here:
            cartpage = new mycartpage();
            cartpage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cartbtnActionPerformed

    private void ignorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignorebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ignorebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ReservationsPage().setVisible(true);
            }
        });
    }
    
   
    private BusServices busservicespage;
    private EventsPage eventspage;
    private HomePage homepage;
    private mycartpage cartpage;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JButton buservicesbtn;
    private javax.swing.JButton cartbtn;
    private javax.swing.JButton eventsbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton ignorebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
