/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sohaib Ali
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelabel = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        contactlabel = new javax.swing.JLabel();
        contactfield = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        signupbtn = new javax.swing.JButton();
        signupbtn1 = new javax.swing.JButton();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        namelabel.setText("NAME :");
        getContentPane().add(namelabel);
        namelabel.setBounds(130, 370, 50, 40);

        namefield.setText("jTextField1");
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield);
        namefield.setBounds(210, 380, 290, 22);

        emaillabel.setText("EMAIL :");
        getContentPane().add(emaillabel);
        emaillabel.setBounds(130, 430, 60, 40);

        emailfield.setText("jTextField1");
        getContentPane().add(emailfield);
        emailfield.setBounds(210, 440, 290, 22);

        contactlabel.setText("CONTACT :");
        getContentPane().add(contactlabel);
        contactlabel.setBounds(130, 480, 70, 40);

        contactfield.setText("jTextField1");
        getContentPane().add(contactfield);
        contactfield.setBounds(210, 490, 290, 22);

        passwordlabel.setText("PASSWORD :");
        getContentPane().add(passwordlabel);
        passwordlabel.setBounds(130, 540, 80, 40);

        passwordfield.setText("jTextField1");
        getContentPane().add(passwordfield);
        passwordfield.setBounds(210, 550, 290, 22);

        signupbtn.setText("SIGN UP NOW !");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signupbtn);
        signupbtn.setBounds(860, 530, 140, 40);

        signupbtn1.setText("Login");
        signupbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(signupbtn1);
        signupbtn1.setBounds(860, 470, 140, 40);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup1366x768.png"))); // NOI18N
        getContentPane().add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void adminSignup(String username, String email, String password, String contact) throws SQLException
    {
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select count(*) from `scd_db`.`Admin`";
        PreparedStatement ps =con.prepareStatement(sql);  
        
        ResultSet rs = ps.executeQuery();
        rs.next();
        
        int count = rs.getInt("count(*)");
        count++;
        
        sql = "INSERT INTO `scd_db`.`Admin` VALUES(?, ?, ?, ?, ?);";
        ps = con.prepareStatement(sql);
        
        ps.setInt(1, count);
        ps.setString(2, username);
        ps.setString(3, email);
        ps.setString(4, password);
        ps.setString(5, contact);
        
        JOptionPane.showMessageDialog(null, "You are successfuly registered as an Admin !!!");
        
        ps.executeUpdate();
        
        
        
    }
    
    private void customerSignup(String username, String email, String password, String contact) throws SQLException
    {
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select count(*) from `scd_db`.`Customer`";
        PreparedStatement ps =con.prepareStatement(sql);  
        
        ResultSet rs = ps.executeQuery();
        rs.next();
        
        int count = rs.getInt("count(*)");
        count++;
        
        sql = "INSERT INTO `scd_db`.`Customer` VALUES(?, ?, ?, ?, ?, ?, ?);";
        ps = con.prepareStatement(sql);
        
        ps.setInt(1, count);
        ps.setString(2, username);
        ps.setString(3, email);
        ps.setString(4, password);
        ps.setString(5, contact);
        ps.setString(6, "0");
        ps.setString(7, "0");
        
        
        JOptionPane.showMessageDialog(null, "You are successfuly registered as a Customer !!!");
        
        ps.executeUpdate();
    }
    
    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        
        
        String username = namefield.getText();
        String email = emailfield.getText();
        String password = passwordfield.getText();
        String contact = contactfield.getText();
        
        if(username.charAt(0) == '@')
        {
            Connection con;
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select `scd_db`.`Admin`.`Name` from `scd_db`.`Admin` ";
                PreparedStatement ps =con.prepareStatement(sql);
                
                ResultSet rs = ps.executeQuery();
                boolean found = false;
                
                while(rs.next())
                {
                    if(username.equals(rs.getString("Name")))
                    {
                        System.out.println("Admin Already Exists !!!");
                        found = true;
                               
                        break;
                    }
                    
                }
                
                if(!found)
                {
                                            
                        System.out.println("Hello New Admin !!!");
                        try {
                            adminSignup(username, email, password, contact);
                        } catch (SQLException ex) {
                            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }

            

            
        }
        else
        {         
            Connection con;
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select `scd_db`.`Customer`.`Name` from `scd_db`.`Customer` ";
                PreparedStatement ps =con.prepareStatement(sql);
                
                ResultSet rs = ps.executeQuery();
                boolean found = false;
                
                while(rs.next())
                {
                    if(username.equals(rs.getString("Name")))
                    {
                        System.out.println("Customer Already Exists !!!");
                        found = true;
                               
                        break;
                    }
                    
                }
                
                if(!found)
                {
                                            
                        System.out.println("Hello New Customer !!!");
                        try {
                            customerSignup(username, email, password, contact);
                        } catch (SQLException ex) {
                            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }

            

            
        }
       
    }//GEN-LAST:event_signupbtnActionPerformed

    private void signupbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtn1ActionPerformed
        try {
            // TODO add your handling code here:
            
            this.dispose();
            HomePage H = new HomePage();
            H.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signupbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JButton signupbtn;
    private javax.swing.JButton signupbtn1;
    // End of variables declaration//GEN-END:variables
}
