/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1920x1080project;

import java.sql.*;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkg1920x1080project.BusServices.SelectedBusService;
import static pkg1920x1080project.EventsPage.SelectedEvent;
import static pkg1920x1080project.LogInPage.LoggedInUsername;

/**
 *
 * @author Sohaib Ali
 */
public class ViewBusDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewBusDetails
     */
    public ViewBusDetails() throws SQLException {
        initComponents();
        
        populate();
    }
    
    public void populate() throws SQLException
    {
        Connection con;
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select * from `scd_db`.`BusService` where `scd_db`.`BusService`.`Name` = ?";
        
        PreparedStatement ps =con.prepareStatement(sql);  
        
        String name = SelectedBusService;
        ps.setString(1, name);
            
        ResultSet rs = ps.executeQuery();
        rs.next();
        
        
        busnamelabel.setText(rs.getString("Name"));
        fromcitylabel.setText(rs.getString("DepCity"));
        tocitylabel.setText(rs.getString("ArrivalCity"));
        datelabel.setText(rs.getString("Date"));
        pricelabel.setText(rs.getString("TicketPrice"));
    }
    
    private String getBusServiceID()
    {
             try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select `scd_db`.`BusService`.`BusServiceID` from `scd_db`.`BusService` where `scd_db`.`BusService`.`Name` = ?";  
                PreparedStatement ps =con.prepareStatement(sql);
                
                String name = SelectedBusService;
                ps.setString(1, name);

                ResultSet rs = ps.executeQuery();
                rs.next();
                
                String BusServiceID = rs.getString("BusServiceID");
                
                return BusServiceID;
                //con.close();
                
                
            } catch (SQLException ex) {
                Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        return null;
    }
    
    private String getCustomerID()
    {
        try {
                Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select `scd_db`.`Customer`.`CustomerID` from `scd_db`.`Customer` where `scd_db`.`Customer`.`Name` = ?";  
                PreparedStatement ps =con2.prepareStatement(sql);
                
                String name = LoggedInUsername;
                ps.setString(1, name);

                ResultSet rs1 = ps.executeQuery();
                rs1.next();
                
                String CustomerID = rs1.getString("CustomerID");
                System.out.println(CustomerID);
                
                return CustomerID;
            } catch (SQLException ex) {
                Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        return null;
     }
    
    public boolean TicketsAvailability(int tickets) throws SQLException
    {
        Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
        String sql = "Select * from `scd_db`.`BusService` where `scd_db`.`BusService`.`Name` = ?";  
        PreparedStatement ps =con2.prepareStatement(sql);
        
        String name = SelectedBusService;
        ps.setString(1, name);

        ResultSet rs = ps.executeQuery();
        rs.next();
                
        int MaxCapacity = rs.getInt("MaxCapacity");
        int CurrentBookings = rs.getInt("CurrentBookings");
        
        if(tickets + CurrentBookings <= MaxCapacity)
        {
        //    updateCurrentBookings(tickets);
            return true;
        }
        else
        {
            
            JOptionPane.showMessageDialog(null, "You Cannot Book " + tickets + " tickets as only " + (MaxCapacity - CurrentBookings) + " are left");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busnamelabel = new javax.swing.JLabel();
        fromcitylabel = new javax.swing.JLabel();
        tocitylabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        bookticketbtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();
        nooftickets = new javax.swing.JSpinner();
        howmanyticketslabel = new javax.swing.JLabel();
        backgroundlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        busnamelabel.setText("BUS SERVICE NAME LABEL");
        getContentPane().add(busnamelabel);
        busnamelabel.setBounds(640, 40, 200, 40);

        fromcitylabel.setText("FROM CITY LABEL");
        getContentPane().add(fromcitylabel);
        fromcitylabel.setBounds(560, 90, 110, 40);

        tocitylabel.setText("TO CITY LABEL");
        getContentPane().add(tocitylabel);
        tocitylabel.setBounds(760, 90, 90, 40);

        datelabel.setText("DATE LABEL");
        getContentPane().add(datelabel);
        datelabel.setBounds(680, 130, 130, 40);

        timelabel.setText("TIME LABEL");
        getContentPane().add(timelabel);
        timelabel.setBounds(680, 180, 130, 30);

        pricelabel.setText("PRICE LABEL");
        getContentPane().add(pricelabel);
        pricelabel.setBounds(680, 220, 130, 50);

        bookticketbtn.setText("BOOK");
        bookticketbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookticketbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookticketbtn);
        bookticketbtn.setBounds(570, 340, 100, 23);

        returnbtn.setText("RETURN");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbtn);
        returnbtn.setBounds(770, 340, 100, 23);

        nooftickets.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(nooftickets);
        nooftickets.setBounds(680, 290, 64, 22);

        howmanyticketslabel.setText("TICKETS?");
        getContentPane().add(howmanyticketslabel);
        howmanyticketslabel.setBounds(610, 290, 60, 20);

        backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewbusdetails1366x768.png"))); // NOI18N
        getContentPane().add(backgroundlabel);
        backgroundlabel.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookticketbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookticketbtnActionPerformed
        // TODO add your handling code here:
        
        int tickets = (int) nooftickets.getValue();
        boolean available;
        try {
            available = TicketsAvailability(tickets);
            
            if(available == false)
            {
                return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        {
            try {
                String CustomerID = getCustomerID();
                
                Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                String sql = "Select * from  `scd_db`.`BusServiceCart` where `scd_db`.`BusServiceCart`.`CustomerID` = ? ";
                PreparedStatement ps =con2.prepareStatement(sql);
                
                ps.setString(1, CustomerID);
                
                ResultSet rs = ps.executeQuery();
                
                
                String BusServiceID = getBusServiceID();
                while(rs.next())
                {
                    
                    if(BusServiceID.equals(rs.getString("BusServiceID")))
                    {
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
                        String sql1 = "Update `scd_db`.`BusServiceCart` set `scd_db`.`BusServiceCart`.`BusServiceQuantity` = ? where  `scd_db`.`BusServiceCart`.`BusServiceID` = ?";
                        PreparedStatement ps1 =con.prepareStatement(sql1);
                        
                        int BusServiceQuantity = rs.getInt("BusServiceQuantity");
                        int UpdatedBusServiceQuantity = BusServiceQuantity + tickets;
                        ps1.setInt(1, UpdatedBusServiceQuantity);
                        ps1.setString(2, BusServiceID);
                        
                        
                        ps1.executeUpdate();
                        
                        
                        this.dispose();
                        mycartpage cp = new mycartpage();
                        cp.setVisible(true);
                        
                        
                        return;
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
            }
        
      
        
        String BusServiceID = getBusServiceID();;
        String CustomerID = getCustomerID();
        
        
        System.out.println("Event ID : " + BusServiceID);
        System.out.println("CustomerID : " + CustomerID);
        
        
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");        
            String sql = "INSERT INTO `scd_db`.`BusServiceCart` VALUES(?, ?, ?);";
            PreparedStatement ps =con.prepareStatement(sql);  
            
            ps.setString(1, CustomerID);
            ps.setString(2, BusServiceID);
            ps.setInt(3, tickets );
            
            ps.executeUpdate();
            
            this.dispose();
            mycartpage CP = new mycartpage();
            CP.setVisible(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewEventDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookticketbtnActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        try {
            // TODO add your handling code here:
            busservicespage = new BusServices();
            busservicespage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ViewBusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ViewBusDetails().setVisible(true);
            }
        });
    }
    
    
    private BusServices busservicespage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundlabel;
    private javax.swing.JButton bookticketbtn;
    private javax.swing.JLabel busnamelabel;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel fromcitylabel;
    private javax.swing.JLabel howmanyticketslabel;
    private javax.swing.JSpinner nooftickets;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JButton returnbtn;
    private javax.swing.JLabel timelabel;
    private javax.swing.JLabel tocitylabel;
    // End of variables declaration//GEN-END:variables
}
