/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sohaib Ali
 */
public class AddBusFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBusFrame
     */
    public AddBusFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        capacityfield = new javax.swing.JSpinner();
        datefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        tofield = new javax.swing.JTextField();
        fromfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();

        setClosable(true);
        setTitle("AddBus");
        setMaximumSize(new java.awt.Dimension(410, 350));
        setMinimumSize(new java.awt.Dimension(410, 350));

        jPanel2.setMaximumSize(new java.awt.Dimension(410, 350));
        jPanel2.setMinimumSize(new java.awt.Dimension(410, 350));
        jPanel2.setPreferredSize(new java.awt.Dimension(410, 350));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        capacityfield.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel1.setText("Name");

        jLabel2.setText("Capacity");

        jLabel3.setText("Date");

        jLabel4.setText("Price");

        jLabel5.setText("To");

        jLabel6.setText("From");

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(capacityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(66, 66, 66)
                        .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(addbtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(tofield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66)
                        .addComponent(fromfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(capacityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(addbtn)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fromfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private int getUniqueBusServiceID()
    {
        int BusServiceID = 0;
        try {
            
            
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = " Select count(*) from `scd_db`.`BusService` ";  
            PreparedStatement ps =con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next())
            {
               BusServiceID = rs.getInt("count(*)"); 
               BusServiceID++;
              
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEventFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return BusServiceID;
    }
    
    private boolean checkBusServiceExists(String BusServiceName)
    {
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = "Select `scd_db`.`Bus Service`.`Name` from `scd_db`.`BusService` ";
            PreparedStatement ps =con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            boolean found = false;
            
            while(rs.next())
            {
                if(BusServiceName.equals(rs.getString("Name")))
                {
                    
                    JOptionPane.showMessageDialog(null, "Bus Service Already Exists !!!");
                    found = true;
                    
                    break;
                }
                
            }
            
            if(found)
            {
                return true;
            }
            else
            {
                return false; 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEventFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        return false;   
            
    }
    
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {        
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            
            String BusServiceName = namefield.getText();
            int MaxCapacity = (int) capacityfield.getValue();
            String Date = datefield.getText();
            String TicketPrice = pricefield.getText();
            String ArrivalCity = tofield.getText();
            String DepCity = fromfield.getText();
            
            boolean found = checkBusServiceExists(BusServiceName);
            
            if(found)
            {
                return;
            }
            
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = "INSERT INTO `scd_db`.`BusService` VALUES(?, ?, ?, ?, ?, ?, ?, ?);";  
            PreparedStatement ps =con.prepareStatement(sql);
            
            int BusServiceNameID = getUniqueBusServiceID();
            
            ps.setInt(1, BusServiceNameID);
            ps.setString(2, BusServiceName);
            ps.setInt(3, MaxCapacity);
            ps.setInt(4, 0);
            ps.setString(5, Date);
            ps.setString(6, TicketPrice);
            ps.setString(7, DepCity);
            ps.setString(8, ArrivalCity);
            
            
            
            JOptionPane.showMessageDialog(null, "New Bus Service Added Successfuly !!!");
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AddBusFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
        
    }//GEN-LAST:event_addbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JSpinner capacityfield;
    private javax.swing.JTextField datefield;
    private javax.swing.JTextField fromfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField pricefield;
    private javax.swing.JTextField tofield;
    // End of variables declaration//GEN-END:variables
}
