/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;



import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Sohaib Ali
 */
public class AddEventFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddEventFrame
     */
    public AddEventFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        datefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        capacityfield = new javax.swing.JSpinner();
        addbtn = new javax.swing.JButton();
        locationfield = new javax.swing.JTextField();
        locationlabel = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add Event");
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName(""); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Capacity");

        jLabel3.setText("Date");

        jLabel4.setText("Price");

        capacityfield.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        locationlabel.setText("Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationlabel))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namefield)
                            .addComponent(capacityfield, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(datefield)
                            .addComponent(pricefield)
                            .addComponent(locationfield))
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(capacityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(addbtn)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationlabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getUniqueEventID()
    {
        int EventID = 0;
        try {
            
            
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = " Select count(*) from `scd_db`.`Event` ";  
            PreparedStatement ps =con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next())
            {
               EventID = rs.getInt("count(*)"); 
               EventID++;
              
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEventFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return EventID;
    }
    
    private boolean checkEventExists(String EventName)
    {
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = "Select `scd_db`.`Event`.`Name` from `scd_db`.`Event` ";
            PreparedStatement ps =con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            boolean found = false;
            
            while(rs.next())
            {
                if(EventName.equals(rs.getString("Name")))
                {
                    
                    JOptionPane.showMessageDialog(null, "Event Already Exists !!!");
                    found = true;
                    
                    break;
                }
                
            }
            
            if(found)
            {
                return true;
            }
            else
            {
                return false; 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEventFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        return false;   
            
    }
    
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            // TODO add your handling code here:
            
            String EventName = namefield.getText();
            int MaxCapacity = (int) capacityfield.getValue();
            String Date = datefield.getText();
            String TicketPrice = pricefield.getText();
            String Location = locationfield.getText();
            
            boolean found = checkEventExists(EventName);
            
            if(found)
            {
                return;
            }
            
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scd_db", "root", "123456");
            String sql = "INSERT INTO `scd_db`.`Event` VALUES(?, ?, ?, ?, ?, ?, ?);";  
            PreparedStatement ps =con.prepareStatement(sql);
            
            int EventID = getUniqueEventID();
            
            ps.setInt(1, EventID);
            ps.setString(2, EventName);
            ps.setInt(3, MaxCapacity);
            ps.setInt(4, 0);
            ps.setString(5, Date);
            ps.setString(6, TicketPrice);
            ps.setString(7, Location);


            
            JOptionPane.showMessageDialog(null, "New Event Added Successfuly !!!");
            ps.executeUpdate();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEventFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JSpinner capacityfield;
    private javax.swing.JTextField datefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationfield;
    private javax.swing.JLabel locationlabel;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField pricefield;
    // End of variables declaration//GEN-END:variables
}
